import { useState } from 'react'
import { motion } from 'framer-motion'
import ResultCard from './ResultCard'
import { downloadReportAsPDF } from '../utils/pdfExport'
import { useClipboard } from '../hooks/useClipboard'
import { extractDomain } from '../utils/urlUtils'

/**
 * Extracts likely tech stack tags from the techStack section text.
 * Looks for known technology names in the content.
 */
function extractTechTags(text) {
  if (!text) return []
  const known = [
    'React', 'Vue', 'Angular', 'Next.js', 'Nuxt', 'Svelte', 'Remix',
    'TypeScript', 'JavaScript', 'Python', 'Ruby', 'PHP', 'Go', 'Java',
    'Node.js', 'Express', 'Django', 'Rails', 'Laravel', 'FastAPI',
    'Tailwind', 'Bootstrap', 'SCSS', 'CSS Modules',
    'AWS', 'Vercel', 'Netlify', 'Cloudflare', 'GCP', 'Azure',
    'PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'Supabase', 'Firebase',
    'GraphQL', 'REST', 'tRPC', 'WebSockets',
    'Docker', 'Kubernetes', 'GitHub', 'GitLab',
    'Stripe', 'Shopify', 'WordPress', 'Webflow',
  ]
  return known.filter(tech =>
    text.toLowerCase().includes(tech.toLowerCase())
  ).slice(0, 8)
}

/**
 * Extracts security severity tags from security section text.
 */
function extractSecurityTags(text) {
  if (!text) return []
  const tags = []
  if (/https|ssl|tls/i.test(text)) tags.push('HTTPS ✓')
  if (/csp|content.security/i.test(text)) tags.push('CSP')
  if (/xss/i.test(text)) tags.push('XSS Risk')
  if (/csrf/i.test(text)) tags.push('CSRF')
  if (/cookie/i.test(text)) tags.push('Cookies')
  if (/hsts/i.test(text)) tags.push('HSTS')
  if (/cors/i.test(text)) tags.push('CORS')
  if (/mixed.content/i.test(text)) tags.push('Mixed Content')
  return tags.slice(0, 6)
}

/**
 * AnalysisResults — displays the complete AI analysis report.
 */
export default function AnalysisResults({ result, url, onReset }) {
  const [isPDFLoading, setIsPDFLoading] = useState(false)
  const { copy: copyAll, isCopied: isAllCopied } = useClipboard()
  const domain = extractDomain(url)
  const techTags = extractTechTags(result.techStack)
  const securityTags = extractSecurityTags(result.security)

  const handleDownloadPDF = async () => {
    setIsPDFLoading(true)
    try {
      await downloadReportAsPDF(url, result)
    } catch (e) {
      console.error('PDF generation failed:', e)
    } finally {
      setIsPDFLoading(false)
    }
  }

  const handleCopyAll = () => {
    const fullReport = `
WEBSITE ANALYSIS REPORT — ${domain}
Generated by ExplainMyWebsite
URL: ${url}
Date: ${new Date().toLocaleString()}
${'='.repeat(50)}

🧠 SUMMARY
${result.summary}

⚙️ TECH STACK
${result.techStack}

🎨 UI/UX FEEDBACK
${result.uiUx}

🔐 SECURITY OBSERVATIONS
${result.security}
    `.trim()
    copyAll(fullReport)
  }

  return (
    <motion.div
      className="relative z-10 max-w-6xl mx-auto px-6 pb-16"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
    >
      {/* Report header */}
      <motion.div
        className="glass-card p-5 mb-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4"
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="flex items-center gap-3">
          {/* Success indicator */}
          <div className="relative w-10 h-10 flex-shrink-0">
            <div className="absolute inset-0 rounded-full bg-accent-3/10 border border-accent-3/30 flex items-center justify-center">
              <svg className="w-5 h-5 text-accent-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
          </div>
          <div>
            <p className="font-display font-semibold text-white">
              Analysis complete for{' '}
              <span className="text-accent font-mono">{domain}</span>
            </p>
            <p className="text-xs text-muted font-mono mt-0.5 truncate max-w-xs sm:max-w-sm">{url}</p>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-2 flex-wrap">
          {/* Copy all */}
          <motion.button
            onClick={handleCopyAll}
            className="flex items-center gap-2 px-3 py-2 rounded-xl border border-border text-muted hover:text-white hover:border-accent/40 hover:bg-accent/5 transition-all text-xs font-mono"
            whileTap={{ scale: 0.96 }}
          >
            {isAllCopied ? (
              <><svg className="w-3.5 h-3.5 text-accent-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg> Copied!</>
            ) : (
              <><svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg> Copy Report</>
            )}
          </motion.button>

          {/* Download PDF */}
          <motion.button
            onClick={handleDownloadPDF}
            disabled={isPDFLoading}
            className="flex items-center gap-2 px-3 py-2 rounded-xl border border-border text-muted hover:text-white hover:border-accent-2/40 hover:bg-accent-2/5 transition-all text-xs font-mono disabled:opacity-50 disabled:cursor-not-allowed"
            whileTap={{ scale: 0.96 }}
          >
            {isPDFLoading ? (
              <><svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg> Generating...</>
            ) : (
              <><svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg> Download PDF</>
            )}
          </motion.button>

          {/* Analyze new */}
          <motion.button
            onClick={onReset}
            className="flex items-center gap-2 px-3 py-2 rounded-xl bg-accent text-white hover:bg-accent/90 transition-all text-xs font-display font-semibold"
            whileTap={{ scale: 0.96 }}
          >
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
            </svg>
            New Analysis
          </motion.button>
        </div>
      </motion.div>

      {/* Cards grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        <ResultCard
          emoji="🧠"
          title="Summary"
          subtitle="What this website does"
          content={result.summary}
          accentColor="#7c6aff"
          delay={0.05}
        />

        <ResultCard
          emoji="⚙️"
          title="Tech Stack"
          subtitle="Inferred technologies"
          content={result.techStack}
          accentColor="#6affda"
          delay={0.15}
          tags={techTags}
        />

        <ResultCard
          emoji="🎨"
          title="UI/UX Feedback"
          subtitle="Design & experience observations"
          content={result.uiUx}
          accentColor="#ff6a9e"
          delay={0.25}
        />

        <ResultCard
          emoji="🔐"
          title="Security Observations"
          subtitle="Basic security assessment"
          content={result.security}
          accentColor="#ffb460"
          delay={0.35}
          tags={securityTags}
        />
      </div>

      {/* Disclaimer */}
      <motion.p
        className="text-center text-xs text-muted mt-8 max-w-xl mx-auto leading-relaxed"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.6 }}
      >
        ⚠️ AI analysis is generated automatically and may not be 100% accurate. 
        Tech stack guesses and security observations are inferences — always verify independently.
      </motion.p>
    </motion.div>
  )
}
